### ISSUE TITLE
[Story] Improve data handling of book lists

### ISSUE THREAD

**Issue by BrenekH** [Dylan-Gresham/BookTrack#23]
As a user, I need to have book list data saved and transferred between the frontend and backend so that I can view and modify my previous lists.

**Acceptance Criteria:**
- [x] Given a book list, when the save routine is ran, then book list data is saved in the user config
- [x] Given a newly launched program, when book list data is present in the backend, then it should be sent to the frontend

**Comment by Dylan-Gresham** [comment]
Implemented with 98ed66250332f55585a30a0dfb53cd51a2f93588 and 6e9d4f81b17b20f0e24c1d2a91df1538bff2274d
