### ISSUE TITLE
(Task) Figure Out Why New Accounts Aren't Being Created

### ISSUE THREAD

**Issue by Dylan-Gresham** [Dylan-Gresham/BookTrack#37]
References user story #1 

For some reason when new accounts are created and then redirected to the home route, no account is being found. This is a research task to determine why this happening.

**Comment by BrenekH** [comment]
The issue is that the main page calls to the Tauri state for information about the current user, but the `update_config` command only saves the new user configuration to the filesystem and does not update the Tauri state struct
