### ISSUE TITLE
Add Yourself to Footer Credits

### ISSUE THREAD

**Issue by Dylan-Gresham** [Dylan-Gresham/BookTrack#6]
# Add Yourself to Footer Credits

Add your name and a link to your GitHub to the Footer component.

- [x] Dylan (update current format)
- [x] Brenek
- [x] Cisco

**Comment by Dylan-Gresham** [comment]
Dylan footer credit complete with commit 35cf01b010520b4898f4575fa6f7741f7f9764dd

**Comment by BrenekH** [comment]
Brenek footer added in 4f73a9a

**Comment by FranciscoMurguia** [comment]
Name and github added to footer 049e31e
